name: nexus_store_workspace

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    updateGitTagRefs: true
    workspaceChangelog: true

scripts:
  analyze:
    run: dart analyze --fatal-infos
    exec:
      concurrency: 1
    description: Run dart analyze in all packages

  test:
    run: dart test
    packageFilters:
      dirExists: test
    description: Run tests in all packages

  test:coverage:
    run: dart test --coverage=coverage
    packageFilters:
      dirExists: test
    description: Run tests with coverage

  build:runner:
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: Run build_runner in packages that need it

  format:
    run: dart format .
    description: Format all Dart code

  format:check:
    run: dart format --set-exit-if-changed .
    description: Check formatting without making changes

  clean:
    run: |
      rm -rf .dart_tool
      rm -rf build
      rm -rf coverage
    exec:
      concurrency: 1
    description: Clean build artifacts
