builders:
  nexus_store_riverpod:
    import: "package:nexus_store_riverpod_generator/builder.dart"
    builder_factories: ["nexusStoreRiverpodBuilder"]
    build_extensions: {".dart": [".nexus_store.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
